const KZN_LOCATION_DATA = [

  // DURBAN / ETHEKWINI

  { name: "Amanzimtoti", city: "Durban" },
  { name: "Asherville", city: "Durban" },
  { name: "Avoca", city: "Durban" },
  { name: "Berea", city: "Durban" },
  { name: "Bluff", city: "Durban" },
  { name: "Chatsworth", city: "Durban" },
  { name: "Clairwood", city: "Durban" },
  { name: "Cato Manor", city: "Durban" },
  { name: "Cato Ridge", city: "Durban" },
  { name: "Congella", city: "Durban" },
  { name: "Durban Central", city: "Durban" },
  { name: "Escombe", city: "Durban" },
  { name: "Folweni", city: "Durban" },
  { name: "Glenwood", city: "Durban" },
  { name: "Hammersdale", city: "Durban" },
  { name: "Inanda", city: "Durban" },
  { name: "Isipingo", city: "Durban" },
  { name: "Isipingo Hills", city: "Durban" },
  { name: "KwaMashu", city: "Durban" },
  { name: "Lamontville", city: "Durban" },
  { name: "KwaMakhutha", city: "Durban" },
  { name: "Malvern", city: "Durban" },
  { name: "Mariannhill", city: "Durban" },
  { name: "Mayville", city: "Durban" },
  { name: "Montclair", city: "Durban" },
  { name: "Mount Edgecombe", city: "Durban" },
  { name: "Merebank", city: "Durban" },
  { name: "Newlands", city: "Durban" },
  { name: "Newlands East", city: "Durban" },
  { name: "Newlands West", city: "Durban" },
  { name: "North Beach", city: "Durban" },
  { name: "Ntuzuma", city: "Durban" },
  { name: "Overport", city: "Durban" },
  { name: "Pinetown", city: "Durban" },
  { name: "Queensburgh", city: "Durban" },
  { name: "Reservoir Hills", city: "Durban" },
  { name: "Shallcross", city: "Durban" },
  { name: "Sherwood", city: "Durban" },
  { name: "South Beach", city: "Durban" },
  { name: "Sydenham", city: "Durban" },
  { name: "Umlazi", city: "Durban" },
  { name: "Umbilo", city: "Durban" },
  { name: "Umgeni", city: "Durban" },
  { name: "Umhlanga", city: "Durban" },
  { name: "Verulam", city: "Durban" },
  { name: "Waterfall", city: "Durban" },
  { name: "Westville", city: "Durban" },
  { name: "Wentworth", city: "Durban" },
  { name: "Yellowwood Park", city: "Durban" },

  // NORTH COAST

  { name: "Ballito", city: "KwaDukuza" },
  { name: "KwaDukuza", city: "KwaDukuza" },
  { name: "Stanger", city: "KwaDukuza" },
  { name: "Salt Rock", city: "KwaDukuza" },
  { name: "Shakaskraal", city: "KwaDukuza" },
  { name: "Tongaat", city: "Tongaat" },
  { name: "Dolphin Coast", city: "Ballito" },
  { name: "Sundumbili", city: "Mandeni" },
  { name: "Mandeni", city: "Mandeni" },
  { name: "Mtunzini", city: "Mtunzini" },
  { name: "Empangeni", city: "Empangeni" },
  { name: "Richards Bay", city: "Richards Bay" },
  { name: "Esikhaleni", city: "Richards Bay" },
  { name: "KwaMbonambi", city: "Richards Bay" },
  { name: "Nseleni", city: "Richards Bay" },

  // PIETERMARITZBURG / MIDLANDS

  { name: "Pietermaritzburg", city: "Pietermaritzburg" },
  { name: "Ashburton", city: "Pietermaritzburg" },
  { name: "Hayfields", city: "Pietermaritzburg" },
  { name: "Imbali", city: "Pietermaritzburg" },
  { name: "Edendale", city: "Pietermaritzburg" },
  { name: "Scottsville", city: "Pietermaritzburg" },
  { name: "Northdale", city: "Pietermaritzburg" },
  { name: "Woodlands", city: "Pietermaritzburg" },
  { name: "Howick", city: "Howick" },
  { name: "Mooi River", city: "Mooi River" },
  { name: "Nottingham Road", city: "Nottingham Road" },
  { name: "Estcourt", city: "Estcourt" },
  { name: "Greytown", city: "Greytown" },
  { name: "Wartburg", city: "Wartburg" },

  // SOUTH COAST

  { name: "Amanzimtoti", city: "Durban" },
  { name: "Kingsburgh", city: "Kingsburgh" },
  { name: "Doonside", city: "Kingsburgh" },
  { name: "Warner Beach", city: "Kingsburgh" },
  { name: "Scottburgh", city: "Scottburgh" },
  { name: "Pennington", city: "Pennington" },
  { name: "Sezela", city: "Sezela" },
  { name: "Hibberdene", city: "Hibberdene" },
  { name: "Port Shepstone", city: "Port Shepstone" },
  { name: "Shelly Beach", city: "Shelly Beach" },
  { name: "Margate", city: "Margate" },
  { name: "Ramsgate", city: "Ramsgate" },
  { name: "Uvongo", city: "Uvongo" },
  { name: "Port Edward", city: "Port Edward" },

  // NORTHERN KWAZULU-NATAL

  { name: "Newcastle", city: "Newcastle" },
  { name: "Madadeni", city: "Newcastle" },
  { name: "Osizweni", city: "Newcastle" },
  { name: "Dundee", city: "Dundee" },
  { name: "Glencoe", city: "Glencoe" },
  { name: "Ladysmith", city: "Ladysmith" },
  { name: "Ezakheni", city: "Ladysmith" },
  { name: "Bergville", city: "Bergville" },
  { name: "Vryheid", city: "Vryheid" },
  { name: "Ulundi", city: "Ulundi" },
  { name: "Nongoma", city: "Nongoma" },
  { name: "Pongola", city: "Pongola" },
  { name: "Jozini", city: "Jozini" },
  { name: "Mkuze", city: "Mkuze" },

  // KZN EASTERN AREAS

  { name: "Port St Johns", city: "Port St Johns" },
  { name: "Kokstad", city: "Kokstad" },
  { name: "Harding", city: "Harding" },
  { name: "Ixopo", city: "Ixopo" },
  { name: "Creighton", city: "Creighton" },
  { name: "Underberg", city: "Underberg" },
  { name: "Himeville", city: "Himeville" }

];